#!/bin/sh
#CameraMEM_V1
#Eric Huang 2013

	echo "Testing is started at `date`..."
	`date > "/data/local/tmp/procrank-CameraMEM.log"`
	`ps >> "/data/local/tmp/procrank-CameraMEM.log"`
	`date > "/data/local/tmp/meminfo-original.log"`
	`cat /proc/meminfo >> "/data/local/tmp/meminfo-original.log"`
	export busyboxpath="/data/local/tmp/busybox"
	export package="com.android.gallery3d/com.android.camera.CameraLauncher"
	export string="PID"
	r=0
	dontstop=0
	takeapicture=0
	takefail=0
	launchfail=0
	homefail=0

	if [ "$1" == 0 ]
	then
		dontstop=1
	fi

	am start -n $package
	for i in 1 2 3 4 5
		do
			input keyevent 4
		done


	while [ "$r" != `$busyboxpath expr $1 - $dontstop ` ]
		do
			r=`$busyboxpath expr $r + 1 `
			for i in 1 2 3 4 5
				do
					input keyevent 4
				done
			sleep 5s
			if [ "$2" == 1 ]
			then
				mv /mnt/sdcard/DCIM/Camera/* /mnt/sdcard/DCIM/Camera_picture
			fi
			rm -r /mnt/sdcard/DCIM/Camera/*
			export state=`dumpsys media.camera|$busyboxpath grep -i $string`
			export check=`[ -z "$state" ] ; echo $?`
			if [ "$check" == 0 ]
				then
					am start -n $package
					sleep 10s
					export state=`dumpsys media.camera|$busyboxpath grep -i $string`
					export check=`[ -z "$state" ] ; echo $?`
					if [ "$check" == 1 ]
						then
							input keyevent 27
							echo "Take a picture"
							sleep 5s
							export picture=`$busyboxpath find /mnt/sdcard/DCIM/Camera/ -type f |$busyboxpath wc -l`
							if [ "$picture" != 0 ]
								then
									takeapicture=`$busyboxpath expr $takeapicture + 1 `
									echo "Take a picture for $takeapicture cycle(s)"
									if [ `$busyboxpath expr $r % 300 ` -eq 0 ]
									then
										`echo "Take a picture PASS for $takeapicture cycle(s)" >> "/data/local/tmp/procrank-CameraMEM.log"`
										`date >> "/data/local/tmp/procrank-CameraMEM.log"`
										`ps >> "/data/local/tmp/procrank-CameraMEM.log"`
										echo "Record the memory info"
									fi
									sleep 5s
								else
									takefail=`$busyboxpath expr $takefail + 1 `
									echo "take the picture FAIL for $takefail cycle(s)"
									if [ `$busyboxpath expr $r % 300 ` -eq 0 ]
									then
										`echo "take the picture FAIL for $takefail cycle(s)" >> "/data/local/tmp/procrank-CameraMEM.log"`
										`date >> "/data/local/tmp/procrank-CameraMEM.log"`
										`ps >> "/data/local/tmp/procrank-CameraMEM.log"`
										echo "Record the memory info"
									fi
							fi
						else
							launchfail=`$busyboxpath expr $launchfail + 1 `
							echo "launch camera FAIL for $launchfail cycle(s)"
							if [ `$busyboxpath expr $r % 300 ` -eq 0 ]
							then
								`echo "launch camera FAIL for $launchfail cycle(s)" >> "/data/local/tmp/procrank-CameraMEM.log"`
								`date >> "/data/local/tmp/procrank-CameraMEM.log"`
								`ps >> "/data/local/tmp/procrank-CameraMEM.log"`
								echo "Record the memory info"
							fi
					fi
				else
					homefail=`$busyboxpath expr $homefail + 1 `
					echo "stop the camera FAIL for $homefail cycle(s)"
					if [ `$busyboxpath expr $r % 300 ` -eq 0 ]
					then
						`echo "stop the camera FAIL for $homefail cycle(s)" >> "/data/local/tmp/procrank-CameraMEM.log"`
						`date >> "/data/local/tmp/procrank-CameraMEM.log"`
						`ps >> "/data/local/tmp/procrank-CameraMEM.log"`
						echo "Record the memory info"
					fi
			fi


			echo "Testing is finish at `date`..."
			`date > "/data/local/tmp/meminfo-aftertest.log"`
			`cat /proc/meminfo >> "/data/local/tmp/meminfo-aftertest.log"`


			`echo "Total test Time: $r round" > "/data/local/tmp/TestResult.txt"`
			`echo "Take a picture PASS for $takeapicture cycle(s)" >> "/data/local/tmp/TestResult.txt"`
			`echo "take the picture FAIL for $takefail cycle(s)" >> "/data/local/tmp/TestResult.txt"`
			`echo "launch camera FAIL for $launchfail cycle(s)" >> "/data/local/tmp/TestResult.txt"`
			`echo "stop the camera FAIL for $homefail cycle(s)" >> "/data/local/tmp/TestResult.txt"`
			echo `uptime` >> "/data/local/tmp/TestResult.txt"
		done


	if [ "$2" == 1 ]
		then
		mv /mnt/sdcard/DCIM/Camera/* /mnt/sdcard/DCIM/Camera_picture
	fi

	rm -r /mnt/sdcard/DCIM/Camera/*
	for i in 1 2 3 4 5
		do
			input keyevent 4
		done





